apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: {{ .Values.acs.namespace }}
data:
  runtime_config.yaml: |
    networking:
      externalIps:
  {{- if .Values.acs.collector.config.external_ips_enable }}
        enabled: ENABLED
  {{- else }}
        enabled: DISABLED
  {{- end }}