---

subDomain: __OVERWRITE_ME__

ConsoleLinks:
  keycloak:
    enabled: false
    href: 'https://sso.{{ .Values.subDomain }}'
  keycloakRealm:
    enabled: false
    href: 'https://sso.{{ .Values.subDomain }}/realms/{{ .Values.keycloakRealm.name }}/account'

keycloak:
  namespace: __OVERWRITE_ME__
  name: keycloak

  database:
    vendor: __OVERWRITE_ME__
    host: __OVERWRITE_ME__
    name: __OVERWRITE_ME__
    secretName: __OVERWRITE_ME__

  route:
    # The host for the Keycloak route, this is the URL Keycloak will respond to.
    host: "sso.{{ .Values.subDomain }}"
    tls:
      # Toggles the TLS configuration for the Keycloak route, when disabled the
      # endpoint exposed is HTTP only.
      enabled: true
      secretName: &keycloakRouteTLSSecretName keycloak-tls
      termination: reencrypt
    annotations:
      route.openshift.io/termination: reencrypt
  
  service:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: *keycloakRouteTLSSecretName      

keycloakRealm:
  namespace: __OVERWRITE_ME__
  name: tssc-realm
  adminUsername: __OVERWRITE_ME__
  adminPassword: __OVERWRITE_ME__
  adminEmail: __OVERWRITE_ME__
  adminSecretName: tssc-realm-admin-user
  tas:
    enabled: false
    clientID: trusted-artifact-signer
    clientSecretName: trusted-artifact-signer-client-secret
    IssuerURL: "https://sso.{{ .Values.subDomain }}/realms/{{ .Values.keycloakRealm.name }}"
    clients:
      tas:
        enabled: true      
  tpa:
    enabled: false
    clientID: trusted-profile-analyzer
    clientSecretName: trusted-profile-analyzer-client-secret
    IssuerURL: "https://sso.{{ .Values.subDomain }}/realms/{{ .Values.keycloakRealm.name }}"
    clients:
      cli:
        enabled: true
      testingManager:
        enabled: false
      testingUser:
        enabled: false
    frontendRedirectUris:
      - "http://localhost:8080"
      - "https://server-trusted-profile-analyzer.{{ .Values.subDomain }}"
      - "https://server-trusted-profile-analyzer.{{ .Values.subDomain }}/*"
      - "https://sbom-trusted-profile-analyzer.{{ .Values.subDomain }}"
      - "https://sbom-trusted-profile-analyzer.{{ .Values.subDomain }}/*"        
    integrationSecret:
      # Bombastic API URL.
      bombasticAPI: https://server-trusted-profile-analyzer.{{ .Values.subDomain }}
      # OIDC client ID to interact with the Bombastic API endpoint.
      clientID: cli
      # Secret namespace and name.
      namespace: trusted-profile-analyzer
      name: tssc-trustification-integration
      # CycloneDX version supported by TPA (Trustification).
      cycloneDXVersion: 1.4            