---
subDomain: __OVERWRITE_ME__

consoleLinks:
  quay:
    enabled: false

quay:
  name: quay-registry
  namespace: quay
  clairVolumeSize: 100Gi
  objectStorageManaged: false
  configBundle:
    registryTitle: "Quay Container Registry"
    serverHostname: "quay-registry.{{ .Values.subDomain }}"
    superUsers:
     - quayadmin
    featureUserInitialize: true
    quayS3Region: "us-east-1"
    quayS3Endpoint: "https://minio-api.{{ .Values.subDomain }}" 
    quayS3AccessKey: __OVERWRITE_ME__
    quayS3SecretKey: __OVERWRITE_ME__