apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.minio.name }}-api
  namespace: {{ .Values.minio.namespace }}
  labels:
    app: minio
spec:
  host: {{ .Values.minio.route.api.host }}.{{ .Values.subDomain }}
  to:
    kind: Service
    name: minio
    weight: 100
  port:
    targetPort: api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.minio.name }}-console
  namespace: {{ .Values.minio.namespace }}
  labels:
    app: minio
spec:
  host: {{ .Values.minio.route.console.host }}.{{ .Values.subDomain }}
  to:
    kind: Service
    name: minio
    weight: 100
  port:
    targetPort: console
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None