---
operators:
  keycloak:
    enabled: false
    description: Red Hat Build of Keycloak Operator
    apiResource: keycloaks.k8s.keycloak.org
    namespace: keycloak
    name: rhbk-operator
    channel: stable-v26.4
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
      targetNamespaces:
        - keycloak
  openshiftPipelines:
    enabled: false
    description: OpenShift Pipelines Operator
    namespace: openshift-operators
    name: openshift-pipelines-operator-rh
    channel: pipelines-1.21
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  trustedArtifactSigner:
    enabled: false
    description: Red Hat Trusted Artifact Signer Operator
    apiResource: securesigns.rhtas.redhat.com
    namespace: trusted-artifact-signer-operator
    name: rhtas-operator
    channel: stable-v1.3
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default 
  trustedProfileAnalyzer:
    enabled: false
    description: Red Hat Trusted Profile Analyzer Operator
    apiResource: trustedprofileanalyzers.rhtpa.io
    namespace: trusted-profile-analyzer-operator
    name: rhtpa-operator
    channel: stable-v1.1
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
      targetNamespaces:
        - trusted-profile-analyzer
  advancedClusterSecurity:
    enabled: false
    description: Red Hat Advanced Cluster Security Operator
    apiResource: centrals.platform.stackrox.io
    channel: rhacs-4.9
    namespace: acs-operator
    name: rhacs-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
  minio:
    enabled: false
    description: AIStor MinIO Operator - High-performance S3-compatible object storage 
    apiResource: aistor.min.io/v1
    channel: stable
    namespace: aistor
    name: minio-object-store-operator
    source: certified-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
  quay:
    enabled: false
    description: The Red Hat Quay Operator deploys and manages a production-ready container registry based on Quay.
    apiResource: quay.redhat.com/v1
    channel: stable-3.16
    namespace: quay
    name: quay-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
      targetNamespaces:
        - quay
  gitea:
    enabled: false
    description: The Gitea Operator
    apiResource: gitea.com/v1
    channel: stable
    namespace: gitea
    name: gitea-operator
    source: redhat-rhpds-gitea
    sourceNamespace: gitea
    catalogSource:
      type: grpc
      name: redhat-rhpds-gitea
      image: quay.io/rhpds/gitea-catalog:v2.1.0
      displayName: Red Hat Demo Platform (Gitea)
      publisher: Red Hat Demo Platform
    operatorGroup:
      upgradeStrategy: Default