---
subDomain: __OVERWRITE_ME__

consoleLinks:
  minio:
    enabled: false

minio:
  name: minio-objectstore
  adminUser:
    username: __OVERWRITE_ME__
    password: __OVERWRITE_ME__
  namespace: minio
  secretName: minio-user
  storageSize: 50Gi
  image: 
    name: minio
    repository: "quay.io/minio/"
    pullPolicy: IfNotPresent
    tag: "RELEASE.2025-04-22T22-12-26Z"
  route:
    api:
      host: minio-api
    console:
      host: minio-console