---
postgres:
  namespace: postgres
  podName: pgsql
  secretName: pgsql-user
  storageSize: 10Gi
  image:
    name: postgresql-16
    repository: "registry.redhat.io/rhel10/"
    pullPolicy: IfNotPresent
    tag: "10.1"
  service:
    name: pgsql
    type: ClusterIP
    port: 5432
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  database:
    name: __OVERWRITE_ME__
    user: __OVERWRITE_ME__
    password: __OVERWRITE_ME__